modLoader="javafml"
loaderVersion="[28,)"
#issueTrackerURL=""

[[mods]] #mandatory
modId="immersivepetroleum"
version="${file.jarVersion}"
displayName="Immersive Petroleum"
displayURL="https://minecraft.curseforge.com/projects/immersive-petroleum"
authors="Flaxbeard"
description="Adds oil and oil processing features to Immersive Engineering."
#updateJSONURL=""
#credits=""
#logoFile=""

[[dependencies.immersiveengineering]]
	modId="immersiveengineering"
	mandatory=true
	versionRange="[0.14-95,)"
	ordering="BEFOR"
	side="BOTH"

[[dependencies.immersivepetroleum]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.immersivepetroleum]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
